name: "Build, lint, and test"
on: [pull_request, workflow_dispatch]
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  test:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Start emulator
        timeout-minutes: 20
        run: scripts/start_emulator.sh
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check gradle version
        run: ./gradlew --version
      - name: Evaluate ktlint
        run: ./gradlew ktlintCheck
      - name: Build
        run: ./gradlew assembleStagingDebug
      - name: Evaluate Android linter
        run: ./gradlew lint
      - name: Run unit tests
        run: ./gradlew testStagingDebugUnitTest
      - name: Run instrumentation tests
        run: ./gradlew stagingDebugExecuteScreenshotTests
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Reports
          path: app/build/reports/

